//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECollectWebServices.Coupon
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.avisortech.com/eCollectWebservices", ConfigurationName="ECollectWebServices.Coupon.eCollectWebservicesv4Soap")]
    public interface eCollectWebservicesv4Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.avisortech.com/eCollectWebservices/getTransactionInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ECollectWebServices.Coupon.getTransactionInformationResponseType> getTransactionInformationAsync(ECollectWebServices.Coupon.getTransactionInformationType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.avisortech.com/eCollectWebservices/createTransactionPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ECollectWebServices.Coupon.createTransactionResponseType> createTransactionPaymentAsync(ECollectWebServices.Coupon.createTransactionType request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class getTransactionInformationType
    {
        
        private string entityCodeField;
        
        private string ticketIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntityCode
        {
            get
            {
                return this.entityCodeField;
            }
            set
            {
                this.entityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TicketId
        {
            get
            {
                return this.ticketIdField;
            }
            set
            {
                this.ticketIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class createTransactionResponseType
    {
        
        private string returnCodeField;
        
        private string ticketIdField;
        
        private string eCollectUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TicketId
        {
            get
            {
                return this.ticketIdField;
            }
            set
            {
                this.ticketIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string eCollectUrl
        {
            get
            {
                return this.eCollectUrlField;
            }
            set
            {
                this.eCollectUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class subserviceType
    {
        
        private string entityCodeField;
        
        private string srvCodeField;
        
        private string valueTypeField;
        
        private decimal transValueField;
        
        private decimal transVatValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntityCode
        {
            get
            {
                return this.entityCodeField;
            }
            set
            {
                this.entityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SrvCode
        {
            get
            {
                return this.srvCodeField;
            }
            set
            {
                this.srvCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ValueType
        {
            get
            {
                return this.valueTypeField;
            }
            set
            {
                this.valueTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal TransValue
        {
            get
            {
                return this.transValueField;
            }
            set
            {
                this.transValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal TransVatValue
        {
            get
            {
                return this.transVatValueField;
            }
            set
            {
                this.transVatValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class itemType
    {
        
        private string itemCodeField;
        
        private string flagDBCRField;
        
        private int itemQtyField;
        
        private string itemDescField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ItemCode
        {
            get
            {
                return this.itemCodeField;
            }
            set
            {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FlagDBCR
        {
            get
            {
                return this.flagDBCRField;
            }
            set
            {
                this.flagDBCRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ItemQty
        {
            get
            {
                return this.itemQtyField;
            }
            set
            {
                this.itemQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ItemDesc
        {
            get
            {
                return this.itemDescField;
            }
            set
            {
                this.itemDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class createTransactionType
    {
        
        private string entityCodeField;
        
        private string srvCodeField;
        
        private decimal transValueField;
        
        private decimal transVatValueField;
        
        private string srvCurrencyField;
        
        private string uRLResponseField;
        
        private string uRLRedirectField;
        
        private string signField;
        
        private string signFieldsField;
        
        private string[] referenceArrayField;
        
        private string paymentSystemField;
        
        private string fICodeField;
        
        private string invoiceField;
        
        private string policyCodeField;
        
        private string[] authReferenceArrayField;
        
        private itemType[] itemArrayField;
        
        private subserviceType[] subservicesArrayField;
        
        private AdditionalInfoType[] additionalInfoArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntityCode
        {
            get
            {
                return this.entityCodeField;
            }
            set
            {
                this.entityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SrvCode
        {
            get
            {
                return this.srvCodeField;
            }
            set
            {
                this.srvCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal TransValue
        {
            get
            {
                return this.transValueField;
            }
            set
            {
                this.transValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal TransVatValue
        {
            get
            {
                return this.transVatValueField;
            }
            set
            {
                this.transVatValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SrvCurrency
        {
            get
            {
                return this.srvCurrencyField;
            }
            set
            {
                this.srvCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string URLResponse
        {
            get
            {
                return this.uRLResponseField;
            }
            set
            {
                this.uRLResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string URLRedirect
        {
            get
            {
                return this.uRLRedirectField;
            }
            set
            {
                this.uRLRedirectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Sign
        {
            get
            {
                return this.signField;
            }
            set
            {
                this.signField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SignFields
        {
            get
            {
                return this.signFieldsField;
            }
            set
            {
                this.signFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceArray", Order=9)]
        public string[] ReferenceArray
        {
            get
            {
                return this.referenceArrayField;
            }
            set
            {
                this.referenceArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PaymentSystem
        {
            get
            {
                return this.paymentSystemField;
            }
            set
            {
                this.paymentSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FICode
        {
            get
            {
                return this.fICodeField;
            }
            set
            {
                this.fICodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Invoice
        {
            get
            {
                return this.invoiceField;
            }
            set
            {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PolicyCode
        {
            get
            {
                return this.policyCodeField;
            }
            set
            {
                this.policyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public string[] AuthReferenceArray
        {
            get
            {
                return this.authReferenceArrayField;
            }
            set
            {
                this.authReferenceArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemArray", Order=15)]
        public itemType[] ItemArray
        {
            get
            {
                return this.itemArrayField;
            }
            set
            {
                this.itemArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubservicesArray", Order=16)]
        public subserviceType[] SubservicesArray
        {
            get
            {
                return this.subservicesArrayField;
            }
            set
            {
                this.subservicesArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalInfoArray", Order=17)]
        public AdditionalInfoType[] AdditionalInfoArray
        {
            get
            {
                return this.additionalInfoArrayField;
            }
            set
            {
                this.additionalInfoArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class AdditionalInfoType
    {
        
        private string infoCodeField;
        
        private string infoDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InfoCode
        {
            get
            {
                return this.infoCodeField;
            }
            set
            {
                this.infoCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InfoData
        {
            get
            {
                return this.infoDataField;
            }
            set
            {
                this.infoDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class retriesTicketIdType
    {
        
        private string ticketIdField;
        
        private string tranStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TicketId
        {
            get
            {
                return this.ticketIdField;
            }
            set
            {
                this.ticketIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TranState
        {
            get
            {
                return this.tranStateField;
            }
            set
            {
                this.tranStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class operationType
    {
        
        private string operCodeField;
        
        private string flagDBCRField;
        
        private string operDescField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OperCode
        {
            get
            {
                return this.operCodeField;
            }
            set
            {
                this.operCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FlagDBCR
        {
            get
            {
                return this.flagDBCRField;
            }
            set
            {
                this.flagDBCRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OperDesc
        {
            get
            {
                return this.operDescField;
            }
            set
            {
                this.operDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.avisortech.com/eCollectWebservices")]
    public partial class getTransactionInformationResponseType
    {
        
        private string entityCodeField;
        
        private string ticketIdField;
        
        private string trazabilityCodeField;
        
        private string tranStateField;
        
        private string returnCodeField;
        
        private decimal transValueField;
        
        private decimal transVatValueField;
        
        private string payCurrencyField;
        
        private decimal currencyRateField;
        
        private System.DateTime bankProcessDateField;
        
        private string fICodeField;
        
        private string bankNameField;
        
        private string paymentSystemField;
        
        private string transCycleField;
        
        private string invoiceField;
        
        private string[] referenceArrayField;
        
        private string[] authReferenceArrayField;
        
        private operationType[] operationArrayField;
        
        private retriesTicketIdType[] retriesTicketIdField;
        
        private AdditionalInfoType[] additionalInfoArrayField;
        
        private string srvCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntityCode
        {
            get
            {
                return this.entityCodeField;
            }
            set
            {
                this.entityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TicketId
        {
            get
            {
                return this.ticketIdField;
            }
            set
            {
                this.ticketIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TrazabilityCode
        {
            get
            {
                return this.trazabilityCodeField;
            }
            set
            {
                this.trazabilityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TranState
        {
            get
            {
                return this.tranStateField;
            }
            set
            {
                this.tranStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal TransValue
        {
            get
            {
                return this.transValueField;
            }
            set
            {
                this.transValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal TransVatValue
        {
            get
            {
                return this.transVatValueField;
            }
            set
            {
                this.transVatValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PayCurrency
        {
            get
            {
                return this.payCurrencyField;
            }
            set
            {
                this.payCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal CurrencyRate
        {
            get
            {
                return this.currencyRateField;
            }
            set
            {
                this.currencyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime BankProcessDate
        {
            get
            {
                return this.bankProcessDateField;
            }
            set
            {
                this.bankProcessDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FICode
        {
            get
            {
                return this.fICodeField;
            }
            set
            {
                this.fICodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string BankName
        {
            get
            {
                return this.bankNameField;
            }
            set
            {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PaymentSystem
        {
            get
            {
                return this.paymentSystemField;
            }
            set
            {
                this.paymentSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TransCycle
        {
            get
            {
                return this.transCycleField;
            }
            set
            {
                this.transCycleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Invoice
        {
            get
            {
                return this.invoiceField;
            }
            set
            {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceArray", Order=15)]
        public string[] ReferenceArray
        {
            get
            {
                return this.referenceArrayField;
            }
            set
            {
                this.referenceArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public string[] AuthReferenceArray
        {
            get
            {
                return this.authReferenceArrayField;
            }
            set
            {
                this.authReferenceArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OperationArray", Order=17)]
        public operationType[] OperationArray
        {
            get
            {
                return this.operationArrayField;
            }
            set
            {
                this.operationArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RetriesTicketId", Order=18)]
        public retriesTicketIdType[] RetriesTicketId
        {
            get
            {
                return this.retriesTicketIdField;
            }
            set
            {
                this.retriesTicketIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalInfoArray", Order=19)]
        public AdditionalInfoType[] AdditionalInfoArray
        {
            get
            {
                return this.additionalInfoArrayField;
            }
            set
            {
                this.additionalInfoArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string SrvCode
        {
            get
            {
                return this.srvCodeField;
            }
            set
            {
                this.srvCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface eCollectWebservicesv4SoapChannel : ECollectWebServices.Coupon.eCollectWebservicesv4Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class eCollectWebservicesv4SoapClient : System.ServiceModel.ClientBase<ECollectWebServices.Coupon.eCollectWebservicesv4Soap>, ECollectWebServices.Coupon.eCollectWebservicesv4Soap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public eCollectWebservicesv4SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(eCollectWebservicesv4SoapClient.GetBindingForEndpoint(endpointConfiguration), eCollectWebservicesv4SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public eCollectWebservicesv4SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(eCollectWebservicesv4SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public eCollectWebservicesv4SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(eCollectWebservicesv4SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public eCollectWebservicesv4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ECollectWebServices.Coupon.getTransactionInformationResponseType> getTransactionInformationAsync(ECollectWebServices.Coupon.getTransactionInformationType request)
        {
            return base.Channel.getTransactionInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ECollectWebServices.Coupon.createTransactionResponseType> createTransactionPaymentAsync(ECollectWebServices.Coupon.createTransactionType request)
        {
            return base.Channel.createTransactionPaymentAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.eCollectWebservicesv4Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.eCollectWebservicesv4Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            //if ((endpointConfiguration == EndpointConfiguration.eCollectWebservicesv4Soap))
            //{
            //    return new System.ServiceModel.EndpointAddress("https://test1.e-collect.com/app_express/webservice/eCollectWebservicesv4.asmx");
            //}
            //if ((endpointConfiguration == EndpointConfiguration.eCollectWebservicesv4Soap12))
            //{
            //    return new System.ServiceModel.EndpointAddress("https://test1.e-collect.com/app_express/webservice/eCollectWebservicesv4.asmx");
            //}
            if ((endpointConfiguration == EndpointConfiguration.eCollectWebservicesv4Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.e-collect.com/app_express/webservice/eCollectWebservicesv2.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.eCollectWebservicesv4Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.e-collect.com/app_express/webservice/eCollectWebservicesv2.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            eCollectWebservicesv4Soap,
            eCollectWebservicesv4Soap12,
        }
    }
}